### ISSUE TITLE
Code of Conduct / Community Rules in Hebrew

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#1]
Will want to prettify [it](https://tooot.im/about/more) in other ways as well. (see [toot.cafe](https://toot.cafe/about/more) and [toot.cat](https://toot.cat/about/more) for examples), and modify it in ways that reflect actual emerging netiquette on the site, e.g. intolerance to follow bots.

**Comment by msappir** [comment]
@yair please add links to toot.cafe and toot.cat CoCs

**Comment by msappir** [comment]
Also I can translate (it's my former profession) if nobody else volunteers...

**Comment by yair** [comment]
You're welcome to both. :)

**Comment by msappir** [comment]
Okay, killing time still waiting for that damn technician, I'm on it.

**Comment by msappir** [comment]
<div dir="rtl">
אוקיי, יש אצלי גם תרגום מלא עם התאמות קלות של מה שמופיע אצלנו כרגע, אבל אחרי זה הכנתי משהו שמבוסס יותר על הכללים של טוט.קאט, וזה נראה לי הרבה יותר מוצלח. הכנסתי לזה לא מעט מדעותיי האישיות ואני לא רוצה שנעלה את זה לאוויר בלי שנתתם את דעתכם על זה, קחו את הזמן.

# כללי הקהילה בשרת זה
משתמשי tooot.im ("השרת") מסכימים לקיים סביבה מכילה ומכבדת עבור כל משתמשי/ות השרת.

## עיקר הכללים:
- לא להטריד, להתקיף, להשפיל או לאיים
- אם מישהו/י מבקש/ת להפסיק אינטראקציה כלשהי, להפסיק מיד
- לנסות לאפשר מרחב נעים ומכיל עבור כולןם
- לא להציג באופן גלוי תכנים פורנוגרפיים או קשים
- אפס סובלנות לגזענות, כולל כל התבטאות כהניסטית או נאצית

## מנהלים:
- יאיר (@yair)
- מיכאל (@abgd) 
כללי הקהילה הם לא מסמך משפטי, אלא נועדו לאפשר הבנה של הגישה שלנו לניהול השרת. ייתכנו פעולות מנהלתיות על בסיס שאינו מתואר בכללים אלו.

## כללים קהילתיים מפורטים יותר
אנו שואפים למרחב משותף ללא דיכוי ודורסנות, במובן של שפה והתנהגות המבטאות, מחזקות, או מעודדות כל צורה של עליונות חברתית מערכתית.
בקהילה זו איננו מקבלים:
- הטרדה או התנפלות
- התקפות אישיות
- הערות תוקפניות או משפילות
- צורות אחרות של התנהלות ושפה דכאנית

דוגמאות להתנהלות נפוצה שיכולה להחשב כהטרדה:
- המשך אינטראקציה עם משתמש/ת שביקש/ה באופן ברור להפסיק את האינטראקציה הזו, או עידוד משתמשים אחרים לעשות זאת.
- איסוף או הפצה של נתונים דמוגרפיים או פרטיים של אדם ללא רשותו המוצהרת (פרקטיקה המכונה לעתים doxing).

### תכנים אסורים
תוכן מהסוגים הבאים בפידים הפומביים יוסר בלי אזהרה, ויכול להוביל לחסימת הגישה שלך לשירות:
- גזענות או תמיכה בגזענות
- סקסיזם או תמיכה בסקסיזם
- להטבופוביה או תמיכה בלהטבופוביה
- שנאת זרים ו/או לאומנות אלימה

חשבונות שמשמשים באופן קבוע להפיץ תוכן מהסוגים הנ"ל, גם אם לא באופן פומבי לחלוטין, ייחסמו לצמיתות.

תוכן מהסוגים הבאים אסור לחלוטין ויגרור חסימה מיידית:
- הצגה מינית של ילדים/ות
- תוכן שעובר על החוק בצרפת ובגרמניה (שם מאוכסן השרת), כולל הכחשת שואת היהודים והצגת סמלים נאציים
- תוכן המקדם אידיאולוגיה נאצית או כהניסטית


### תכנים רגישים
יש סוגי תוכן אותם אנחנו שואפים לא להציג באופן גלוי לכל, אלא להשתמש בכלים להסתרת תוכן (CW לטקסט, NSFW לתמונות) להסתרתם מעיניים שלא בוחרות לראות אותם. כמובן שגם לא נציג תוכן כזה לעיני כל בתמונת הפרופיל או בתיאור האישי בפרופיל שלנו.

תכנים שאנחנו מסתירים כוללים:
- תוכן פורנוגרפי או מיני מאוד
- כל תוכן המציג אלימות (כולל ייצוגים גרפיים של אנשים מתים וחיות מתות, ושל אנשים חמושים)
- אנימציות או סרטונים שמרצדים או משתנים במהירות


כל משתמשי/ות השרת מקבלות על עצמן לשאוף לקיים את כללים אלו ולפעול נגד תכנים והתנהלות שעוברים עליהם. בפרט אנו מעודדים את כל המשתמשים/ות לדווח על תוכן שמפריע להן כדי להביאו לתשומת לב מנהלי השרת.

### רובוטים
אנחנו שרת ידידותי לרובוטים, עד גבול מסוים.
- אפס סובלנות ל- followbots (רובוטים שעוקבים אחרי כל משתמש שהם רואים ברשת המבוזרת בשביל לאכלס את הפידים בשרת הבית שלהם)
- מעט מאוד סובלנות לרובוטים שמספימים, לדעתנו, את הפידים בפרסומים אוטומטיים מוגזמים
- אפס סובלנות לרובוטים שעוברים על כללי השרת

### שרתים חסומים
יש שרתים ברשת המבוזרת שלא ניתן להתחבר איתם דרך השרת כי הם חסומים. הרשימה המעודכנת עם הסיבות לחסימה נמצאת [בגיטהאב.](https://github.com/Toootim/blocked-instances)

### קנרית צא"פ – 1 במאי 2017
השרת לא קיבל אף מכתב רשמי או צו תחת איסור פרסום. הודעה זו תתעדכן עד 1 באוגוסט 2017 אם מצב זה לא השתנה.

</div>

**Comment by msappir** [comment]
@yair @seefood @mux2000 @eyal6699
אני גם אשים לפה קישור עוד מעט מחיצרוץ

**Comment by yair** [comment]
הערה אחת עובדתית - השרת המרכזי הוא בצרפת, אבל שרת התמונות בגרמניה, אז אנחנו שואפים לשמור על החוק בשתיהן.

**Comment by msappir** [comment]
אערוך בהתאם.

**Comment by eyalSci** [comment]
"נתונים דמוגרפיים" לא ממש מובן בעיני. אני מציע להשאיר "נתונים פרטיים" בלבד שמעביר בעצמו את הכוונה.

**Comment by msappir** [comment]
קיבלתי. עורך מעכשיו במיקום הבא, כדי שהשרשור פה יהיה נהיר יותר:
https://github.com/Toootim/Resources/blob/master/info/draft_code_of_conduct.md

**Comment by hanan-cohen** [comment]
אני חושב שצריך לפרט קצת את הסעיף של התבטאות דכאנית. 

במקום "התנהלות ושפה דכאנית" אני מציע אולי "כתיבה שמטרתה לגרום למשתתפים להפסיק לבטא באופן חופשי את דעותיהם הלגיטימיות או לייצג את זהותם". רק התחלה של רעיון.

**Comment by hanan-cohen** [comment]
בנוגע ל"לא להציג באופן גלוי תכנים פורנוגרפיים או קשים" אני מציע להחליף את "קשים" ב"ייצוג גרפי (או פשוט לכתוב צילומים?) של אלימות וקרבנות אלימות".

**Comment by elad661** [comment]
מציע **להדגיש** את המילים "אסור לחלוטין" במשפט "תוכן מהסוגים הבאים אסור לחלוטין ויגרור חסימה מיידית"

**Comment by msappir** [comment]
@hanan-cohen הכוונה רק לניסוח ב"עיקר הכללים", נכון?
שיניתי ל: "לא להציג באופן גלוי תכנים פורנוגרפיים או ייצוגים של אלימות פיזית" - סבבה, לא? חשוב לי שזה יהיה קצר בחלק הזה.

@elad661 צודק, בוצע

**Comment by msappir** [comment]
אה, וחנן, לגבי התבטאות דכאנית - מסכים שיש צורך בחידוד הניסוח, אבל אין לי פתרון לזה בשלוף. מקווה לחזור לזה הערב. :)

**Comment by msappir** [comment]
בעקבות סערת המטא הנוכחית: צריך להוסיף איסור על צילום מסך של חצרוצים שאינם פומביים ופרסומם מחוץ להקשר הרצוי.
(זה מן הסתם דבר שקשה לאכוף, אבל בכל זאת כשמתגלה שמישהו עושה את הדבר הנבזי הזה צריך להעיף אותו...)

**Comment by eyalSci** [comment]
מסכים, אבל זה צריך להיות רק על חצרוצים לעוקבים בלבד. כלומר, שיהיה בסדר לצלמסך חצרוצים לא רשומים (הרי קשה מאוד להבדיל ביניהם לחצרוצים פומביים). אולי כדאי לכתוב על חצרוצים "פרטיים" (כן, אני מודע לבעייתיות) במקום "לא פומביים".
הייתי שם את זה ב"דוגמאות להתנהלות נפוצה שיכולה להחשב כהטרדה", מתחת לסעיף על דוקסינג.

**Comment by msappir** [comment]
עשיתי עוד כמה שינויים ושיפורים ניסוחיים, אפשר לראות בהיסטוריה של המסמך. עוד לא החלטתי איך לשפר את החלק על התבטאות דכאנית, אני נורא חושש מלהגדיר את זה באופן צר או רחב מדי.

בנושא שאייל העלה בפיד - תמונות של אוכל, בפרט אוכל שעשוי מחיות מתות - חשבתי להוסיף שורה שממליצה, אבל לא דורשת, להסתיר תמונות של אוכל, ובפרט אוכל שמופק מבעלי חיים. נראה לכם סבבה? (אני חושש להיות הטבעוני שכופה את דעתו על קהילה שלמה, אז מאוד אשמח לפידבק על הנושא הזה גם ממי שאוכלים חיות. גם פידבק שלילי זה טוב.)

כנראה שאעלה את הכללים לאוויר היום בכל מקרה, אפשר לשפר אותם גם אחרי כן.

**Comment by msappir** [comment]
רק עכשיו ראיתי את התגובה האחרונה של אייל פה, ובכלל שכחתי להוסיף את זה קודם. הוספתי בדומה לאיך שהצעת:
"יצירה ושיתוף של צילומי מסך של הודעות לעוקבים בלבד או הודעות פרטיות."

**Comment by eyalSci** [comment]
בקשר לאוכל, אני לא בטוח שכדאי לבקש להסתיר את כל התמונות של האוכל בכללים, אלא אם תהיה בקשה לכך.
זה מאוד אינדיבידואלי אבל אוכל צמחוני שמופק מבע"ח פחות מפריע לי ולו בגלל שהוא נראה מאוד דומה לאוכל טבעוני שאני אוכל. לי אישית חיות מתות מפריעות בהרבה.
בכל מקרה, אם נסכים שרק מזון לא צמחוני צריך להסתיר, אני בעד שזה לא יהיה כתוב בכללים במפורש. אלא פשוט נבקש אישית להסתיר להבא. רק אם זה לא יכובד אז אתה או יאיר תתערבו ותפנו לסעיף על הסתרת חיות מתות.

כלומר, מבחינתי מה שחשוב זה לא הניסוח במסמך, אלא הסכמה כללית על הפרשנות אליו.

**Comment by seefood** [comment]
​Do we really want to get down to details like that?
Non-Vegan food is something you will see every day at the supermarket, in
the street or in Shuk HaCarmel, this level of political correctness (hiding
uncomfortable truths) is too reminiscent of Haredi censorship and the like.
it's a very bad precedent.

Not all issues can be upgraded to taboo or we'll have nothing left to
discuss very quickly. Let's say that if it's something legal that you might
bump into on a public street in Jerusalem or Tel Aviv, it should not be
censored by management. If the community wants to reach a self-moderation
agreement that's fine, but putting it down as law is a very bad idea.

**Comment by eyalSci** [comment]
לא נראה לי שהייתי מגדיר תמונה של חיה מתה כ"אמת לא נוחה", אין בה שום ידע שמערער על תפיסת העולם שלי, אם כבר תמונות של אנשים מתים מסוריה למשל הן אלו שמהוות "אמת לא נוחה". 
יש לצורך העניין גם חתולים דרוסים ברחובות תל אביב, והייתי מבין לגמרי אוכלי בשר שיבקשו שאני אסתיר ואזהיר אם אעלה תמונה של חתול דרוס שראיתי ברחוב.
בכל מקרה, מסכים שזה צריך לבוא מלמטה כהחלטה קהילתית, ולא כהחלטה ניהולית של שלושה אנשים. לכן טוב שכמה שיותר אנשים מביעים את דעתם (וזה אגב חיסרון של ניהול הדיון בגיטהאב).

**Comment by msappir** [comment]
העליתי את הגרסה הנוכחית לעמוד האודות: https://tooot.im/about/more

**Comment by seefood** [comment]
<div dir=rtl>סוף סוף הגעתי לקרוא. נהדר, ובמיוחד סעיף קנרית הצא"פ :)

**Comment by msappir** [comment]
יש כבר לא מעט הערות שעלו ועוד לא טופלו... מנסה לרכז את כל מה שאני מוצא עכשיו.
דברים שאני יודע שצריך להוסיף/לשנות:

- [ ] הבהרה שהמנהלים מבטיחים לא לנסות לעקוף את הפרטיות של הודעות או משהו כזה
- [ ] הבהרת המונח "התנפלות"
- [ ] חידוד/הבהרה בנושא התבטאויות דכאניות
- [ ] החרגת חשיפת הטרדות מאיסור צילומי מסך
- [ ] הוספת "ללא בקשת רשות" בנושא צילומי מסך

נושאים שעוד צריך לדון בהם:

- מה היחס לאוכל, ובפרט אוכל מן החי?
- משהו כמו "תות.ים נבנה על בסיס האמונה שהמשתמשים ידעו להפעיל שיקול דעת לגבי מה נכון ומה לא נכון לעשות במסגרת הקהילה" ואז משהו על ניהול עצמי תחת פיקוח והתערבות רק בעת הצורך כאשר הקהילה לא יכולה לעשות את זה בעצמה. -נעםר

**Comment by elad661** [comment]
בגרסה שעלתה באתר דברים שאמורים להיות **מודגשים** לא מודגשים, וחסרה קצת הזחה לרשימות כדי שהן יהיו קריאות יותר

הכוונה (ובשורות נפרדות כדי שיהיה ברור, כי גיטהאב לא אוהב יישור-לימין)

יש לרשימות הגדרת margin-left

במקום margin-right

ולכן הן אינן מוזחות שמאלה כמו שצריך.

**Comment by msappir** [comment]
תוכל בבקשה לפרט את זה ב- #24 ?

**Comment by seefood** [comment]
<div dir=rtl>
שום בעיית כיווניות, פשוט צריך להתחיל כל תשובה עם `&lt;div dir=rtl&gt;`

**Comment by msappir** [comment]
לגנוב רעיונות מפה http://geekfeminism.wikia.com/wiki/Code_of_conduct
