### ISSUE TITLE
Move to adaptive columns

### ISSUE THREAD

**Issue by eyalSci** [Toootim/Discussion#12]
From reasons stated in tooot.im, I think we should move to adaptive columns.
The css code for that is [lines 228-248 here](https://github.com/Toootim/Resources/blob/master/css/ira-toootim-wide-style.css#L228).

**Comment by seefood** [comment]
Are you placing a pull request?

**Comment by msappir** [comment]
I'll try now (God help us)

**Comment by msappir** [comment]
Okay, [created a PR here](https://github.com/Toootim/mastodon/pull/4). Not sure it's quite right but it's a start I guess.
