### ISSUE TITLE
HebTrans crashes preferences page

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#14]
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277] method=GET path=/about/more format=html controller=AboutController action=more status=500 error='ActionView::Template::Error: can not load translations from /mastodon/config/locales/devise.he.yml: #<Psych::SyntaxError: (/mastodon/config/locales/devise.he.yml): found character that cannot start any token while scanning for the next token at line 11 column 16>' duration=367.60 view=0.00 db=0.00
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277] ActionView::Template::Error (can not load translations from /mastodon/config/locales/devise.he.yml: #<Psych::SyntaxError: (/mastodon/config/locales/devise.he.yml): found character that cannot start any token while scanning for the next token at line 11 column 16>):
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     12:
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     13:       .information-board
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     14:         .section
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     15:           %span= t 'about.user_count_before'
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     16:           %strong= number_with_delimiter @instance_presenter.user_count
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     17:           %span= t 'about.user_count_after'
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]     18:         .section
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277]
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277] app/views/about/more.html.haml:15:in `_app_views_about_more_html_haml___956688094725007340_46972347411720'
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277] app/controllers/concerns/localized.rb:24:in `block in set_locale'
web_1        | [7b36adec-f45b-42d0-963c-fdeaf7944277] app/controllers/concerns/localized.rb:23:in `set_locale'

**Comment by seefood** [comment]
a. which branch?
b. why in discussion and not mastodon?
c. works for me.

please close this
