### ISSUE TITLE
שגיאות בממשק העברי של מסטודון

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#15]
עוד שגיאות! עוד!

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25418923/e115c0a6-2a57-11e7-9be0-cca6726168ea.png)
התווית צריכה להיות "פרטיות ההודעות" או "פרטיות החשבון" או "פרטיות ברירת מחדל"

**Comment by msappir** [comment]
השמות לפידים הפומביים,"בסביבה" ו"בפרהסיה", חמודים אבל לא מספיק מדויקים בשביל התרגום הרשמי.
אני מציע שנעביר אותם לגרסה המקוסטמת של תותים, ובתרגום הרשמי הם יהיו "פיד מקומי" ו"פיד פדרטיבי".

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25419001/7645dcec-2a58-11e7-841c-a71f4b775815.png)
יישומים לא כזה ברור. אפליקציות.

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25419036/ad2b2eba-2a58-11e7-9f1e-233af3e2064b.png)
צריך להאחיד את המגדר הלשוני פה - או כשנוספות עוקבות + כמבקשות לעקוב, או כשנוספים עוקבים + כשמבקשים לעקוב. העירבוב מבלבל.

**Comment by eyalSci** [comment]
3 בעיות לדעתי, בסדר חשיבות עולה:
1. שני סימני קריאה יוצר רושם מוגזם, עדיף לדעתי אחד כמו בשפת המקור.
2. סימני הקריאה הם לפני הטקסט, לא אחריו.
3. הניסוח ממוגדר ופונה לגברים בלבד. אני מציע לעבור ל"חיצרוץ", "חצרצו" או חצרץ/י" 

![screenshot from 2017-04-26 08-23-32](https://cloud.githubusercontent.com/assets/8685770/25419178/b86291fa-2a59-11e7-9e1d-6d24f873eb44.png)

**Comment by eyalSci** [comment]
"אימות דו-גורמי" מבלבל, מציע לעבור ל"אימות דו-שלבי".

**Comment by eyalSci** [comment]
ב"יצוא מידע" לא ברור בדיוק איזה מידע מייצאים.
אני מציע להוסיף "רשימת" לפני הנעקבים/חסומים/מושתקים.
או לחילופין, לקשר אותם למשתמש ב"הנעקבים שלך", "משתמשים שחסמת", "משתמשים שהשתקת".

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25420790/70dfe63a-2a62-11e7-9a99-22a95c6468e7.png)
האפשרות השנייה לא מסבירה את עצמה מספיק טוב - לא מצוין שזה בכל זאת פומבי.

**Comment by cidergirl** [comment]
טוב נו, אם יש לכם איזה פיצ׳ר ריקווסט קטן לתת לי, אז תגידו. לאו דווקא קשור לעברית!
(זו אני, חגי, חגי זו אני)

**Comment by msappir** [comment]
אמג @cidergirl יאי אבל רק למה באישיו הזה???

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25432898/0bccfdf0-2a8f-11e7-9362-6b7493fb0bad.png)
ניסוח מוזר, בואו נשנה ל"לחצו כדי לראות"

**Comment by eyalSci** [comment]
לא הספקתי לצלמסך, אבל כל פעם שאני ממונשן מופיעה הנוטיפיקציה "קיבלת פניה מעם @<>"
והניסוח הזה קצת מוזר, עדיף "קיבלת פניה מ @<>"
עדיין זה קצת מציק לי, כי מינשון הוא לא בהכרח פניה אלא יכול להיות אזכור אגבי. אולי "אוזכרת ע"י @<>" מה דעתכם?

**Comment by msappir** [comment]
מסכים.

**Comment by msappir** [comment]
השדרוג ל- 1.3 משנה דברים שישפיעו גם על התרגום. לדוגמה, חיצרוצים פרטיים הם לעוקבים ככלל ולא רק מקומיים עכשיו. https://github.com/tootsuite/mastodon/releases/tag/v1.3

**Comment by msappir** [comment]
"דוחות" בממשק הניהול צריך להיות "דיווחים"

**Comment by seefood** [comment]
יש פיאר בדרך. בדוק אם לא תוקן כבר שם.

**Comment by eyalSci** [comment]
Cancel אמור להיות מתורגם ל"ביטול"
![screenshot from 2017-04-29 15-55-34](https://cloud.githubusercontent.com/assets/8685770/25555667/40bcc064-2cf5-11e7-9d85-0720c8043cde.png)

**Comment by seefood** [comment]
I have translated all the strings. maybe it's an error in the main code. Or
Yair is not running the latest version of Hebrew.

**Comment by yair** [comment]
אכן לקחתי את הגרסא הלא נכונה. :(
איפה אני יכול למצוא את העדכנית?
כמוכן, יש איפשהו את השינוי שעושה ימין לשמאל בעברית?

**Comment by seefood** [comment]
fetch the latest from github and just rebase on translate-hebrew, I just
forced-pushed a definite version for the PR against master.

2017-04-29 16:31 GMT+03:00 Yair <notifications@github.com>:

**Comment by yair** [comment]
Yeah, that blew up spectacularly. I'll just cherry pick what appears to be related.

**Comment by yair** [comment]
כן, זה שבר את האתר באופן מרשים, הפעם אפילו ללא הודעת שגיאה שאפשר דרכה להבין מה נדפק. החזרתי את המצב לקדמותו.

**Comment by seefood** [comment]
I don't understand, my branch broke it?

**Comment by yair** [comment]
Your branch broke my branch, I had to nuke it, clone and cherry-pick.
Your three commits broke the web view. I can send you a pic if you're interested in seeing how.

**Comment by seefood** [comment]
Of course! I always appreciate learning from a good fuckup, my own
included.

**Comment by seefood** [comment]
Also, I can definitely say I hate rebases more each day. I can understand
the attraction, but I hate the headaches it brings.

So now tooot.im has my PR or is it based on the old Hebrew?

**Comment by msappir** [comment]
לכפתור החצרוץ יש סימן קריאה כשהחצרוץ על מצב פומבי, במצבים האחרים אין סימן קריאה (לא רק במצבים בהם יש מנעול של פרטיות)

**Comment by yair** [comment]
Worse. Tooot.im now runs a single Hebrew commit, submitted by me, and which contains the code from toootim/prod (via Beyond Compare). I intend to revert this commit before cherry-picking from the new PR (or accepting it whole if it contains nothing but the Hebrew commits).

**Comment by msappir** [comment]
לגבי סימן הקריאה המיותר על כפתור החצרוץ, זה קבוע בקוד מסתבר:
https://github.com/tootsuite/mastodon/issues/2549

**Comment by yair** [comment]
מה?! אני די משוכנע שכשהרצתי את הגרסה החדשה של עירא היה כתוב בכפתור "חצרוץ" ללא סימן קריאה. :|

**Comment by msappir** [comment]
זה תלוי בדרגת ההפצה שאתה בוחר, כאמור. כשזה על פומבי, יש סימן קריאה. זו אמורה להיות אינדיקציה לזה שזה פומבי, וזו דרך ממש מטומטמת לעשות את זה.

**Comment by seefood** [comment]
אכן, ראיתי שהתלוננו על זה.

**Comment by seefood** [comment]
עובר על השרשור ומסמן :tada: על כל מה שנכנס לתרגום

**Comment by seefood** [comment]
<div dir=rtl>
> אני מציע שנעביר אותם לגרסה המקוסטמת של תותים, ובתרגום הרשמי הם יהיו "פיד מקומי" ו"פיד פדרטיבי".

פיד פדרטיבי לא יאמר הרבה לרוב האנשים. פיד עולמי לא מדויק גם הוא. אז אולי פיד חיצוני או פיד מהעולם?

**Comment by seefood** [comment]
<div dir=rtl>ואגב, מבחינתי האב הרוחני של התרגום הוא @mux2000, אני לא רואה אותו בדיון, לפחות תן הצבעות אגודל מעלה ומטה שיהיה לי כיוון ממך?

**Comment by seefood** [comment]
<div dir=rtl>
> צריך להאחיד את המגדר הלשוני פה - או כשנוספות עוקבות + כמבקשות לעקוב, או כשנוספים עוקבים + כשמבקשים לעקוב. העירבוב מבלבל.

הצעות? כשנוספיםות עוקביםות לא יתקבל בברכה.

שוב, @mux2000 הוא המומחה החסר פה.

**Comment by mux2000** [comment]
בתור האב הרוחני, כמה נקודות שאני רוצה להעלות:

* בכל מקרה, אם קיימת מילה בעברית, אפילו אם אף אחד לא משתמש בה, היא לדעתי עדיפה על המילה הלועזית (לדוגמה, יישומים עדיפה על אפליקציות). מקסימום המשתמשים שלנו ילמדו מילה חדשה, גם טוב.
* בכל מקרה תמיד עדיף למצוא ניסוח נייטרלי מגדרית אם אפשר (לחצרץ). אם לא, אז אפשר להשתמש בסלאש (חצרץ\י), ורק אז ורק במקרי חירום רבים או רבות ("לחצו כדי לראות" למשל). הבעייה שלי עם רבים ורבות, גם אם מעורב זה עדיין מניח ש איזשהו מגדר, והשימוש בסלאש גם מכוער, וגם מניח את קיומו של מגדר בינארי כלשהו. לדוגמה הספיציפית למעלה הצעתי את "בהתחלת עקיבה חדשה אחריך", שהוא ניסוח טיפה עקום, אבל נייטרלי מגדרית, מה שלדעתי לוקח.
* בגלל העדפותי להמנע מלעז נטיתי להשתמש יותר ב"פומבי" ו"פרהסיה" מאשר "פיד פדרציה" וכאלה (לא שאלה מילים עבריות טהורות, אבל טיפה יותר ותיקות בעברית). שמתי לב שגם באנגלית המקורית יש לפידים האלה מיליון שמות, ושמות שונים נמצאים בשימוש במקומות שונים בקוד. לא שזה נותן לנו חופש להשתמש בשמות שונים בעצמנו, לדעתי הכי טוב אם דווקא בתרגום היינו מאחדים ביניהם, רצוי ששם הפיד ילך בעקבות התבנית "בבית" ו"בסביבה" שאני חושב שהחלטתם לשמור? "חיצוני" רומז שלא יהיו שם חצרוצים מהשרת המקומי, מה שלא נכון. מאחר ובלא מעט מקומות בגרסא האנגלית הם משתמשים ב"גלובל פיד" בשביל הפידרציה, אני לא רואה יותר מדי נזק עם לקרוא לזה "בעולם". מה דעתכם?

אני חושב שחפרתי מספיק.

**Comment by seefood** [comment]
<div dir=rtl>
עוד בפרהסיה היית חפרן. אבל עם חזון.

אכן יש כאן ערבוב של ארמית ולך תדע מה, אבל אני ככלל מסכים איתך.

לגבי בבית ובסביבה, אני מאוד מחבב אותם, ומצידי שישארו לתותים, אבל זה לא יתאים לכל מקום. מה לגבי "מהנעשה בקהילה" ו"מקהילות אחרות"? אני משתדל לתרגם אינסטאנס לשרת וסרבר לקהילה (כן, אני יודע שזה מבלבל, אבל לדעתי השפה שז'ניה בחר היא המבלבלת)
</div>

**Comment by seefood** [comment]
hold your fingers...

https://github.com/tootsuite/mastodon/pull/2573/files?diff=unified

(and/or add remarks)

**Comment by mux2000** [comment]
"מהנעשה בקהילה" נשמע כמו עלון של עדי יהווה, ו"מקהילות אחרות", שוב מטעה לחשוב שבפיד הזה לא תראה חצרוצים מהקהילה המקומית.

בגדול אני מאוד אוהב את הדגש על הקהילות וחבריהן על פני השרתים ומשתמשיהם. בכלל "משתמש" ו"שרת" מילים פונקציונאליות נורא ששמות את הדגש על השימוש ולא על הערך. אני לא רואה מצד ה"משתמשים" מה ההבדל בין אינסטנס לשרת. תותים זה תותים ולמי אכפת איפה זה יושב וכמה מחשבים זה בעצם. מצדי הייתי מאחד הכל בממשק המשתמש הכללי, ומשאיר את השרת שרת בממשק האדמין.

**Comment by seefood** [comment]
בתור מי שגדל בכפר ויש לו חברים מקיבוצים, האסוציאציה שלי לא הלכה לשום כיוון
של כת משיחית אבל לבריאות שיהיה. הצעות אחרות מישהי?

**Comment by yair** [comment]
&RLM;s are being rendered as text. See tooot.im

**Comment by eyalSci** [comment]
כן, יש &RLM בכל מקום :(
צריך להוריד את המילה "מקומיים" מהתיאור של "לעוקבים בלבד" בעקבות השינוי של 1.3

**Comment by msappir** [comment]
בשביל תותים אני חושב ש"בעולם" ביחס לפידרציה זה המשך טוב ל"בבית" ו"בסביבה".
בשביל התרגום הרשמי נראה לי חשוב להצמד קרוב לניסוח המקורי כדי שקהילות מסטוש דוברות עברית אחרות יתממשקו באופן שקוף עם הפדרציה. זה דורש שידעו איך קוראים לדברים.
לכן לדעתי בעברית תותית, בסביבה+בעולם, אבל לעברית סאחית, "פיד מקומי" ו"פיד הפדרציה" או משהו כזה.

**Comment by mux2000** [comment]
אני מקבל, רק אולי בלי המילה הלועזית פיד? כלומר "מקומי" ו"פדרציה". אוכל?

**Comment by msappir** [comment]
נראה לי שפיד הופכת במהרה למילה שגרתית בעברית... אולי אפשר "עדכונים מקומיים" ו"עדכונים מהפדרציה" אבל לדעתי עדיף פיד, שוב, בשביל שיהיה יותר קל להבין התייחסויות אליהם באנגלית.

**Comment by msappir** [comment]
כמו כן צריך לתקן "השהיה" (סספנד) ל"השעיה". חחחחח

**Comment by seefood** [comment]
<div dir=rtl>
אוי ואבוי, איך פיספסתי את השהייה? תוקן.

לגבי פיד, אני קורא לזה ציר זמן, או אולי לפעמים זרם (כמו זרם תודעה)

**Comment by seefood** [comment]
"ציר זמן בין-קהילתי"?

**Comment by seefood** [comment]
https://github.com/Toootim/mastodon/commit/fb2d29b28e2c17d74d3ad1b5598984cd5f24781a

For your enjoyment. please add remarks as you see fit.

The lines that are marked as changed but no changes seem visible: I have added Unicode 0x200f for RTL.

if all is right, tonight @yair will deploy this to toootim and I'll make another PR to the master.

**Comment by msappir** [comment]
Might I suggest waiting on the PR until we've tested this on Toootim for at least a few hours? Might save some trouble...

**Comment by yair** [comment]
הוריד את האתר רק לרבע שעה הפעם. אני משתפר. :)
הורדתי ידנית את שני האראלאמים מהדף הראשי, ומבחינתי זה כבר שמיש מספיק כדי להשאר ככה לבינתיים. שמסטודון.סושיאל יהיה אתר הבדיקות שלנו. ;)

**Comment by eyalSci** [comment]
"ציר זמן בין-קהילתי" נשמע לי מאוד מבלבל. אני בעד שימוש פשוט ומובן ב"פיד".
תזכרו, שאנשים מגיעים לרשת פדרטיבית באופן שונה מאוד ממה שהם רגילים אליה, אנחנו צריכים להשתדל כמה שיותר שלא להקשות עליהם. שפה לא ברורה בפירוש מהווה חסם כניסה בעיני.

**Comment by msappir** [comment]
![2017-05-04_10-37-31](https://cloud.githubusercontent.com/assets/7591121/25694140/bce88434-30b5-11e7-9a5d-395b3f729c30.png)
(עוד סמן RLM)

**Comment by msappir** [comment]
![2017-05-04_13-53-50](https://cloud.githubusercontent.com/assets/7591121/25700642/39141c38-30d1-11e7-8273-94946229a201.png)
<div dir="rtl">

- פרטי זה לעוקבים בכלל, לא רק מקומיים

- "לא לפיד הכללי" זה מעולה, אבל הפירוש ארוך מדי, מציע למחוק את המילה "המשותפים"

</div>

**Comment by yair** [comment]
Site downtime: 2 hours
Current version: 1.3.2

**Comment by eyalSci** [comment]
שיא חדש!

**Comment by yair** [comment]
for reference --
TypeError: text.gsub is not a function
    at isRtl (application-ba27252….js:51)
    at StatusContent.value (application-ba27252….js:32)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (application-ba27252….js:776)
    at ReactCompositeComponentWrapper._renderValidatedComponent (application-ba27252….js:776)
    at ReactCompositeComponentWrapper.performInitialMount (application-ba27252….js:776)
    at ReactCompositeComponentWrapper.mountComponent (application-ba27252….js:776)
    at Object.mountComponent (application-ba27252….js:1184)
    at ReactDOMComponent.mountChildren (application-ba27252….js:1116)
    at ReactDOMComponent._createInitialChildren (application-ba27252….js:794)
    at ReactDOMComponent.mountComponent (application-ba27252….js:794)
(anonymous) @ application-ba27252….js:50
(anonymous) @ application-ba27252….js:50
(anonymous) @ application-ba27252….js:1954
dispatch @ application-ba27252….js:1954
(anonymous) @ application-ba27252….js:29

**Comment by yair** [comment]
tooot1.3.3 was somewhat broken, probably by the forced push -- Local trees were all 1 commit ahead and 1 commit behind toootim/tooot1.3.3, even though no local commits were made. I had to revert, pull and merge to avoid conflicts. Not sure what survived. Specifically, some toots containing only Hebrew and tooter-handles are still left justified, so maybe not the RTL stuff. :/
But it's running! And looks great! :D

**Comment by msappir** [comment]
![image](https://cloud.githubusercontent.com/assets/7591121/25793382/d45fb246-33d4-11e7-9871-099b4d0f6181.png)
צריך להיות "חזרה", לא "אחורה" XD
