### ISSUE TITLE
The Fourth Column Became Drawer

### ISSUE THREAD

**Issue by eyalSci** [Toootim/Discussion#19]
Hi, the fourth column function regular, but when I try to reply to toot, it became a place to write toot like 
the drawer.
![screenshot from 2017-05-01 15-05-46](https://cloud.githubusercontent.com/assets/8685770/25579376/01022c2a-2e80-11e7-9258-008c258de19b.png)

**Comment by eyalSci** [comment]
When I started write the toot in one columns, it was written also in the another. So I think it's same object.

**Comment by msappir** [comment]
Steps to reproduce?

**Comment by eyalSci** [comment]
Not sure I understand.

**Comment by eyalSci** [comment]
OK, I don't know if you did anything or not but it just resolved. I close the report.
