### ISSUE TITLE
Mirror main webpage when in an RTL locale

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#22]
So that the tootbox is on the right.

**Comment by seefood** [comment]
this is a question for Gargron or whoever takes charge of the UI. one can make the main theme bi-di/reversible, or add a theming engine to allow users to select between several different themes, some of them can be RTL.
also, there's always the option or a seperate project creating a webUI seperate from the one built into Mastodon, which will connect to your favourite instance via the same API an android app does.

Have you researched what other RTL language developpers are doing so it's not a double effort, or shall I try to investigate?

**Comment by yair** [comment]
You're welcome. I have very little idea how these things work, but I assumed that when a locale is chosen you can change the CSS along with the strings to achieve this effect, or something along these lines.
I mainly wrote this here because it's a usability issue I never thought of that was mentioned in tooot.im and I wanted to preserve it before it's lost. I agree it belongs upstream, but knew you'd notice it faster if it's here. :)
