### ISSUE TITLE
הוספת לינק למדריך בתיאור השרת תותים

### ISSUE THREAD

**Issue by eyalSci** [Toootim/Discussion#23]
היי, נראה לי שכדאי להוסיף את הלינק למדריך למצטרפים חדשים בתיאור השרת. ככה נרשמים חדשים שמגיעים לדף הבית כדי להצטרף יראו אותו מיד.

**Comment by msappir** [comment]
צודק. בוצע:
![image](https://cloud.githubusercontent.com/assets/7591121/25779810/87351aae-3327-11e7-850b-cebf0d40db2e.png)
