### ISSUE TITLE
Donations page

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#6]
Patreon, cryptocurrencies.

**Comment by seefood** [comment]
are you asking or telling?

**Comment by yair** [comment]
I started setting up the Patreon account and plan to open a poloniex account for all the cryptos. Shouldn't take long, but I'm in nearly constant state of putting out fires server-side, so this is always getting shoved down the queue.

**Comment by seefood** [comment]
Ahh. I didn't know it was this unstable. OK, no hurry.

**Comment by msappir** [comment]
This might be worth checking out as another option: https://mastodon.rocks/@Liberapay
