### ISSUE TITLE
Move backup off site (to S3?)

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#7]

**Comment by seefood** [comment]
I use Crashplan, both for my home and servers. pretty good service. S3 is expensive as hell for just this simple use.

**Comment by yair** [comment]
We already use S3 for our media hosting, and keeping the number of suppliers low is a minor priority.
Also, I fail to see how crashplan is cheaper. From their site, $5~$10/month seem to be their price range, while an low-access-frequency S3 bucket costs about $0.014/GB/month (and we only need ~10GB of space).
Ease of use and integration is of course higher priority, as well as integration with the Borg, which is what we're currently using for creating the differential/compressed backups.

**Comment by seefood** [comment]
I pay them $150 annually and back up many terabytes (my family and the server all on the same account) so I see it as cheaper :)
S3 is definitely easier to work with though, no argument, and since there's no fixed-price, it's cheaper at small volumes.

**Comment by yair** [comment]
Using rsync.net
